### ISSUE TITLE
Error when writing to a netCDF file

### ISSUE THREAD

**Issue by hahsan1** [NCAS-CMS/cf-python#206]
Hi,

I am essentially trying to convert a .pp file to .nc using a combination of the cf.read and cf.write functions. I managed to read in the .pp file, however writing out to .nc resulted in an error.

Here is what I tried:
```
import cf
nc = cf.read("bs714a.pm2017jul.pp")
cf.write(nc, 'sample.nc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/decorators.py", line 170, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cf/read_write/write.py", line 647, in write
    netcdf.write(fields, filename, fmt=fmt, overwrite=overwrite,
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/decorators.py", line 170, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 4291, in write
    self._write_field(f)
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 3258, in _write_field
    z_axis = self.implementation.get_construct_data_axes(
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/cfdmimplementation.py", line 506, in get_construct_data_axes
    return field.constructs.data_axes()[key]
KeyError: None
```

My environment is listed below:

Platform: Linux-2.6.32-642.6.2.el6.x86_64-x86_64-with-glibc2.10
HDF5 library: 1.10.6
netcdf library: 4.7.4
udunits2 library: /people/ahsa361/.conda/envs/cmorize/lib/libudunits2.so.0
python: 3.8.8
netCDF4: 1.5.4
cftime: 1.3.0
numpy: 1.19.4
psutil: 5.8.0
scipy: 1.5.2
matplotlib: 3.4.1
ESMF: 8.0.1
cfdm: 1.8.6.0
cfunits: 3.3.1
cfplot: 3.1.0
cf: 3.6.0

**Comment by davidhassell** [comment]
Hello @hahsan1,

Thanks for the report. I wonder if the bug is still present at version 3.8.0? There's nothing obvious in the changelog, but you never know...

If the PP file is available, I'll be happy to take a look.

**Comment by hahsan1** [comment]
Hi @davidhassell,

I updated the version to 3.8.0 but still get a similar error. Here is the traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/decorators.py", line 189, in verbose_override_wrapper
    return method_with_verbose_kwarg(*args, **kwargs)
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cf/read_write/write.py", line 655, in write
    netcdf.write(fields, filename, fmt=fmt, overwrite=overwrite,
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/decorators.py", line 189, in verbose_override_wrapper
    return method_with_verbose_kwarg(*args, **kwargs)
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 4468, in write
    self._write_field(f)
  File "/people/ahsa361/.conda/envs/cmorize/lib/python3.8/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 3430, in _write_field
    z_axis = self.implementation.get_construct_data_axes(
TypeError: 'NoneType' object is not subscriptable
```

This is the updated list of packages. I believe cfdm was also updated to the most recent.

Platform: Linux-2.6.32-642.6.2.el6.x86_64-x86_64-with-glibc2.10
HDF5 library: 1.10.6
netcdf library: 4.7.4
udunits2 library: /people/ahsa361/.conda/envs/cmorize/lib/libudunits2.so.0
Python: 3.8.8
netCDF4: 1.5.4
cftime: 1.3.0
numpy: 1.19.4
psutil: 5.8.0
scipy: 1.5.2
matplotlib: 3.4.1
ESMF: 8.0.1
cfdm: 1.8.8.0
cfunits: 3.3.1
cfplot: 3.1.0
cf: 3.8.0

You can download the file [here](https://dtn2.pnl.gov/data/gcam/CEDS_emissions/test_data/)

**Comment by davidhassell** [comment]
Hi @hahsan1,

I'm afraid that I can't replicate the error, and nothing stands out to me from our environment differences - does anything look relevant to you? (netCDF4 and scipy are not used  by the PP read.)

```python
In [1]: import cf

In [2]: cf.environment(paths=False)
Platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.10
HDF5 library: 1.12.0
netcdf library: 4.7.4
udunits2 library: libudunits2.so.0
Python: 3.8.2
netCDF4: 1.5.6
cftime: 1.4.1
numpy: 1.19.4
psutil: 5.8.0
scipy: 1.6.1
matplotlib: not available
ESMF: 8.0.0
cfdm: 1.8.8.0
cfunits: 3.3.1
cfplot: not available
cf: 3.8.0

In [3]: %time f = cf.read('bs714a.pm2017jul.pp')
CPU times: user 20min 38s, sys: 3.42 s, total: 20min 41s
Wall time: 20min 44s
```

I also tried at proto-v3.9.0 (due 17th May), and it still worked and was ~20x faster (which is one of the purposes of this upcoming release):

```python
In [1]: import cf

In [2]: cf.environment(paths=False)
Platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.10
HDF5 library: 1.12.0
netcdf library: 4.7.4
udunits2 library: libudunits2.so.0
Python: 3.8.2
netCDF4: 1.5.6
cftime: 1.4.1
numpy: 1.19.4
psutil: 5.8.0
scipy: 1.6.1
matplotlib: not available
ESMF: 8.0.0
cfdm: 1.8.9.0
cfunits: 3.3.1
cfplot: not available
cf: 3.9.0

In [3]: %time f = cf.read('bs714a.pm2017jul.pp')
CPU times: user 59 s, sys: 1.53 s, total: 1min
Wall time: 1min 1s
```

**Comment by hahsan1** [comment]
Thanks for trying that out @davidhassell , I guess I can give version 3.9.0 a shot. Is it available for download?

**Comment by davidhassell** [comment]
Hi - `v3.9.0` is now available in conda and PyPI - do let us know if it fixes things ...

Thanks,
David

**Comment by davidhassell** [comment]
Closing this for now - but please re-open if 3.9.0 still doesn't work for you.
Thanks,
David
