### ISSUE TITLE
OSError: dlopen(libudunits2.0.dylib, 6): image not found

### ISSUE THREAD

**Issue by AJamesPhillips** [NCAS-CMS/cf-python#22]
Hi I've tried `import cf` in a python script but it fails with:

```
$ python3 process.py 
Traceback (most recent call last):
  File "process.py", line 1, in <module>
    import cf
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cf/__init__.py", line 134, in <module>
    import cfunits
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfunits/__init__.py", line 36, in <module>
    from .units import Units
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfunits/units.py", line 36, in <module>
    _udunits = ctypes.CDLL('libudunits2.0.dylib')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libudunits2.0.dylib, 6): image not found
```

I am on Mac 10.13.6, pip3 (pip 19.3.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7) )
And xcode: 10.1

pip3 install failed the first time because my xcode was not working but upon rerunning it it appeared to work fine:

```
$ pip3 install cf-python
Collecting cf-python
  Using cached https://files.pythonhosted.org/packages/2d/57/0aaf067f66509538ff0e5f894a77d2750268332b6d3b500e00645e5f9233/cf-python-3.0.5.tar.gz
Requirement already satisfied: netCDF4>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cf-python) (1.5.3)
Requirement already satisfied: cftime>=1.0.4.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cf-python) (1.0.4.2)
Requirement already satisfied: numpy>=1.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cf-python) (1.15.4)
Requirement already satisfied: cfdm>=1.7.10 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cf-python) (1.7.10)
Requirement already satisfied: psutil>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cf-python) (5.6.7)
Requirement already satisfied: cfunits>=3.2.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cf-python) (3.2.2)
Requirement already satisfied: future>=0.16.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from cfdm>=1.7.10->cf-python) (0.18.2)
Installing collected packages: cf-python
    Running setup.py install for cf-python ... done
Successfully installed cf-python-3.0.5
```

**Comment by davidhassell** [comment]
Hi,

It's a problem with the UDUNITS installation. Either it isn't installed and should be (it is not automatically installed by pip, which I should make clearer!); or it is already installed.

In the latter case  you might need to add the UDUNITS binary to you LD_LIBRARY_PATH (https://ncas-cms.github.io/cf-python/installation.html#unidata-udunits-2-library).

Let me know neither of these possibilities work.

**Comment by AJamesPhillips** [comment]
I have it running now.  Thank you very much @davidhassell !

I think the easiest install on a Mac is:

```
brew install expat
brew install udunits
cd /usr/local/lib
ln -s ../Cellar/udunits/2.2.27.6/lib/libudunits2.dylib libudunits2.0.dylib
```
