### ISSUE TITLE
`Field.get_coordinate_reference` errors on bad kwarg

### ISSUE THREAD

**Issue by sadielbartholomew** [NCAS-CMS/cf-python#236]
As-is, with the present cf-python and cfdm `master` branches, `Field.get_coordinate_reference` will always error due to an upstream `TypeError` from an invalid keyword argument in `cfdm`, which ultimately looks like it is case of a missed API conversion in `cfdm` of https://github.com/NCAS-CMS/cfdm/issues/132:

```pycon
>>> import cf
>>> f = cf.example_field(1)
>>> f.get_coordinate_reference()
Traceback (most recent call last):
  File "/home/sadie/cfdm/cfdm/constructs.py", line 1402, in filter
    filter_method = getattr(self, "_" + method)
AttributeError: 'Constructs' object has no attribute '_identity'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sadie/cf-python/cf/mixin/fielddomain.py", line 2283, in get_coordinate_reference
    return self.coordinate_reference(
  File "/home/sadie/cf-python/cf/mixin/fielddomain.py", line 1819, in coordinate_reference
    return self._construct(
  File "/home/sadie/cf-python/cf/mixin/fielddomain.py", line 162, in _construct
    c = getattr(self, _constructs_method)(*identities, **filter_kwargs)
  File "/home/sadie/cfdm/cfdm/mixin/fielddomain.py", line 547, in coordinate_references
    return self._filter_interface(
  File "/home/sadie/cfdm/cfdm/mixin/fielddomain.py", line 278, in _filter_interface
    c = self.constructs.filter(
  File "/home/sadie/cfdm/cfdm/constructs.py", line 1404, in filter
    raise TypeError(
TypeError: Constructs.filter() has an unexpected keyword argument 'identity'
```

#### Fix

This should be an easy fix, so I will self-assign and put in a PR shortly.

#### Env

As observed with:
```pycon
>>> cf.environment(paths=False)
Platform: Linux-4.15.0-54-generic-x86_64-with-glibc2.10
HDF5 library: 1.10.6
netcdf library: 4.8.0
udunits2 library: /home/sadie/anaconda3/envs/cf-env/lib/libudunits2.so.0
Python: 3.8.10
netCDF4: 1.5.6
cftime: 1.5.0
numpy: 1.20.3
psutil: 5.8.0
scipy: 1.6.3
matplotlib: 3.4.2
ESMF: 8.1.1
cfdm: 1.8.9.0
cfunits: 3.3.3
cfplot: 3.1.5
cf: 3.10.0
```

and using the (at time of posting) current `master` branches for both `cf` and `cfdm`.

**Comment by davidhassell** [comment]
Good catch. The offending block is only called when constructs is None, which it always isn't in the library code, which is probably why we've never seen this before.

(Due the appaling lack of documentation in `get_coordinate_reference` (my fault!) I'm struggling to work out what  the `construct` keyword is all about - but that doesn't affect this PR.)
