### ISSUE TITLE
Import fails with `NameError: name 'ESMF' is not defined`

### ISSUE THREAD

**Issue by lguo-uk** [NCAS-CMS/cf-python#263]
Hi there,

I have trouble to make cf python run on my Mac. Below is the details.

Any idea?

Thanks,
Liang

__Installation information:__
```shell
/bin/bash:/Users/liangguo$ pip3 install cf-python
Collecting cf-python
  Downloading cf-python-3.10.0.tar.gz (1.7 MB)
     |████████████████████████████████| 1.7 MB 3.3 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.15 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cf-python) (1.21.2)
Collecting psutil>=0.6.0
  Downloading psutil-5.8.0-cp39-cp39-macosx_10_9_x86_64.whl (236 kB)
     |████████████████████████████████| 236 kB 4.6 MB/s
Collecting cfunits>=3.3.3
  Downloading cfunits-3.3.4.tar.gz (41 kB)
     |████████████████████████████████| 41 kB 1.0 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cfdm<1.8.10.0,>=1.8.9.0
  Downloading cfdm-1.8.9.0.tar.gz (358 kB)
     |████████████████████████████████| 358 kB 1.7 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cftime>=1.5.0
  Downloading cftime-1.5.0-cp39-cp39-macosx_10_9_x86_64.whl (214 kB)
     |████████████████████████████████| 214 kB 4.1 MB/s
Collecting netCDF4>=1.5.4
  Downloading netCDF4-1.5.7-cp39-cp39-macosx_10_9_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 3.6 MB/s
Collecting netcdf-flattener>=1.2.0
  Downloading netcdf-flattener-1.2.0.tar.gz (26 kB)
Building wheels for collected packages: cf-python, cfdm, cfunits, netcdf-flattener
  Building wheel for cf-python (PEP 517) ... done
  Created wheel for cf-python: filename=cf_python-3.10.0-py3-none-any.whl size=1852598 sha256=2cabea76a44faf0d056edde3412d072978ff1c3b32c2eb8bf0b1c1110bbb3bdb
  Stored in directory: /Users/liangguo/Library/Caches/pip/wheels/bf/f3/11/1030e62fed9c830c6ae1108fa7946e53ca99973f27e35c7fce
  Building wheel for cfdm (PEP 517) ... done
  Created wheel for cfdm: filename=cfdm-1.8.9.0-py3-none-any.whl size=436445 sha256=f81eee81a17a23bd664c2c7e93655ecc53d67f9412c3dc2328bbf815c3454762
  Stored in directory: /Users/liangguo/Library/Caches/pip/wheels/74/df/f8/47bd655347815caa68c157064761e7f2f81024af83ba5f0145
  Building wheel for cfunits (PEP 517) ... done
  Created wheel for cfunits: filename=cfunits-3.3.4-py3-none-any.whl size=45745 sha256=8e039b8c48803c6fb6473314bce13d9b9065ba3a5bb097092da20d56ead50a6c
  Stored in directory: /Users/liangguo/Library/Caches/pip/wheels/40/f9/fc/0b2de9906bd26506802cbf3fba3bb6c1fd2fa7a96174fff3ff
  Building wheel for netcdf-flattener (setup.py) ... done
  Created wheel for netcdf-flattener: filename=netcdf_flattener-1.2.0-py3-none-any.whl size=16609 sha256=05cd9987653e36dfbf22f4d29d8c86ab9dbf525695b066c8a9b70df91438bddd
  Stored in directory: /Users/liangguo/Library/Caches/pip/wheels/4e/24/d5/d18bce1186525dd964950eec172be567f8f6ae7387032cb7b2
Successfully built cf-python cfdm cfunits netcdf-flattener
Installing collected packages: cftime, netCDF4, netcdf-flattener, psutil, cfunits, cfdm, cf-python
Successfully installed cf-python-3.10.0 cfdm-1.8.9.0 cftime-1.5.0 cfunits-3.3.4 netCDF4-1.5.7 netcdf-flattener-1.2.0 psutil-5.8.0
```

__Importing cf___
```shell
/bin/bash:/Users/liangguo$ python3
Python 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/__init__.py", line 237, in <module>
    from .field import Field
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/field.py", line 75, in <module>
    from .regrid import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/__init__.py", line 1, in <module>
    from .regridoperator import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py", line 11, in <module>
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
NameError: name 'ESMF' is not defined
```

**Comment by davidhassell** [comment]
Hi Liang,

Thanks for reporting this. It is certainly a bug which we'll fix in the forthcoming release (next week or two, I hope). The offending line is incorrectly indented, and should be inside an `if` clause that is only run if ESMF is installed. 

You can either install ESMF, or else in the meantime, replacing [these two lines](https://github.com/NCAS-CMS/cf-python/blob/master/cf/regrid/regridoperator.py#L8-L9) in `/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py` with (noting the indentation):
```python
    else:
        regrid_method_map = {
```
is a quick fix that should let you get on. If you try this, please let me know how you got on.

David

**Comment by lguo-uk** [comment]
Hi David,

Thanks for the reply. After replacing the Lines 11-12 with suggested code, the script ** regridoperator.py** looks like (with indentation):

```python
from .. import _found_ESMF


if _found_ESMF:
    try:
        import ESMF
    except Exception as error:
        print(f"WARNING: Can not import ESMF for regridding: {error}")
    else:
        regrid_method_map = {
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
    "bilinear": ESMF.RegridMethod.BILINEAR,  # (for back compat)
    "conservative": ESMF.RegridMethod.CONSERVE,
    "conservative_1st": ESMF.RegridMethod.CONSERVE,
    "conservative_2nd": ESMF.RegridMethod.CONSERVE_2ND,
    "nearest_dtos": ESMF.RegridMethod.NEAREST_DTOS,
    "nearest_stod": ESMF.RegridMethod.NEAREST_STOD,
    "patch": ESMF.RegridMethod.PATCH,
}
# ... diverge from ESMF with respect to name for bilinear method by
# using 'linear' because 'bi' implies 2D linear interpolation, which
# could mislead or confuse for Cartesian regridding in 1D or 3D.

regrid_method_map_inverse = {v: k for k, v in regrid_method_map.items()}
...
```

This does not solve the problem, but shift the problem further down to line 24:
```shell
>>> import cf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/__init__.py", line 237, in <module>
    from .field import Field
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/field.py", line 75, in <module>
    from .regrid import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/__init__.py", line 1, in <module>
    from .regridoperator import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py", line 24, in <module>
    regrid_method_map_inverse = {v: k for k, v in regrid_method_map.items()}
NameError: name 'regrid_method_map' is not defined
```

**Comment by lguo-uk** [comment]
On the other hand, if align __else:__ with __if:__ shown above, i.e.:
```python
from .. import _found_ESMF


if _found_ESMF:
    try:
        import ESMF
    except Exception as error:
        print(f"WARNING: Can not import ESMF for regridding: {error}")
else:
    regrid_method_map = {
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
    "bilinear": ESMF.RegridMethod.BILINEAR,  # (for back compat)
    "conservative": ESMF.RegridMethod.CONSERVE,
    "conservative_1st": ESMF.RegridMethod.CONSERVE,
    "conservative_2nd": ESMF.RegridMethod.CONSERVE_2ND,
    "nearest_dtos": ESMF.RegridMethod.NEAREST_DTOS,
    "nearest_stod": ESMF.RegridMethod.NEAREST_STOD,
    "patch": ESMF.RegridMethod.PATCH,
}
# ... diverge from ESMF with respect to name for bilinear method by
# using 'linear' because 'bi' implies 2D linear interpolation, which
# could mislead or confuse for Cartesian regridding in 1D or 3D.

regrid_method_map_inverse = {v: k for k, v in regrid_method_map.items()}
...
```

The same old problem remains:
```
>>> import cf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/__init__.py", line 237, in <module>
    from .field import Field
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/field.py", line 75, in <module>
    from .regrid import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/__init__.py", line 1, in <module>
    from .regridoperator import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py", line 11, in <module>
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
NameError: name 'ESMF' is not defined
```

**Comment by davidhassell** [comment]
Hi Liang,

OK - with my original suggestion, try also  indenting `regrid_method_map_inverse = {v: k for k, v in regrid_method_map.items()}` by 4 spaces...

**Comment by lguo-uk** [comment]
Hi David,

Is this the right way to do?
```python
from .. import _found_ESMF


if _found_ESMF:
    try:
        import ESMF
    except Exception as error:
        print(f"WARNING: Can not import ESMF for regridding: {error}")
else:
    regrid_method_map = {
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
    "bilinear": ESMF.RegridMethod.BILINEAR,  # (for back compat)
    "conservative": ESMF.RegridMethod.CONSERVE,
    "conservative_1st": ESMF.RegridMethod.CONSERVE,
    "conservative_2nd": ESMF.RegridMethod.CONSERVE_2ND,
    "nearest_dtos": ESMF.RegridMethod.NEAREST_DTOS,
    "nearest_stod": ESMF.RegridMethod.NEAREST_STOD,
    "patch": ESMF.RegridMethod.PATCH,
    }
    # ... diverge from ESMF with respect to name for bilinear method by
    # using 'linear' because 'bi' implies 2D linear interpolation, which
    # could mislead or confuse for Cartesian regridding in 1D or 3D.

    regrid_method_map_inverse = {v: k for k, v in regrid_method_map.items()}
...
```

Here is the message:
```shell
>>> import cf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/__init__.py", line 237, in <module>
    from .field import Field
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/field.py", line 75, in <module>
    from .regrid import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/__init__.py", line 1, in <module>
    from .regridoperator import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py", line 11, in <module>
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
NameError: name 'ESMF' is not defined
```

It keeps calling 'ESMF' from
```python
    "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
```

**Comment by davidhassell** [comment]
Hi Liang, try:

**Comment by davidhassell** [comment]
Hi Liang, try:
```python
from .. import _found_ESMF


if _found_ESMF:
    try:
        import ESMF
    except Exception as error:
        print(f"WARNING: Can not import ESMF for regridding: {error}")
    else:
        regrid_method_map = {
        "linear": ESMF.RegridMethod.BILINEAR,  # see comment below...
        "bilinear": ESMF.RegridMethod.BILINEAR,  # (for back compat)
        "conservative": ESMF.RegridMethod.CONSERVE,
        "conservative_1st": ESMF.RegridMethod.CONSERVE,
        "conservative_2nd": ESMF.RegridMethod.CONSERVE_2ND,
        "nearest_dtos": ESMF.RegridMethod.NEAREST_DTOS,
        "nearest_stod": ESMF.RegridMethod.NEAREST_STOD,
        "patch": ESMF.RegridMethod.PATCH,
    }
        # ... diverge from ESMF with respect to name for bilinear method by
        # using 'linear' because 'bi' implies 2D linear interpolation, which
        # could mislead or confuse for Cartesian regridding in 1D or 3D.

        regrid_method_map_inverse = {v: k for k, v in regrid_method_map.items()}
...

**Comment by lguo-uk** [comment]
Here is information:
```python
>>> import cf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/__init__.py", line 237, in <module>
    from .field import Field
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/field.py", line 75, in <module>
    from .regrid import (
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/__init__.py", line 1, in <module>
    from .regridoperator import (
ImportError: cannot import name 'regrid_method_map' from 'cf.regrid.regridoperator' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py)
```

**Comment by davidhassell** [comment]
OK - better leave it there - I have enough information to now to put together a proper, tested pull request that will fix this. Once I've done that it'll be easy to get a _correct_ update to your local code!


Thank you for your help so far - I'll that PR up very soon.

**Comment by davidhassell** [comment]
Hi Liang, I've got a proper patch now. You should be able to install the patch yourself with:

```bash
pip install git+https://github.com/davidhassell/cf-python.git@ESMF-import-fix
```

(P.S. I've changed the title of the issue, because this also affects other OSs)

**Comment by lguo-uk** [comment]
Hi David,

I can run the patch without problem. However, the problem remains.

I've checked the script __/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cf/regrid/regridoperator.py__, nothing seems be altered.

Am I missing something here?

Cheers,
Liang

**Comment by lguo-uk** [comment]
Aha, uninstalling then reinstalling with the new patch solve the problem.

Thanks,
Liang
