### ISSUE TITLE
logger.partitioning is accessed before definition

### ISSUE THREAD

**Issue by lgouldsbrough** [NCAS-CMS/cf-python#274]
logger.partitioning is accessed before definition using Python version: Python 3.8.11; cf-python version 3.11.0 from pypi

Using import cf immediately throws an attribute error: `'Logger' object has no attribute 'partitioning'`. The expected behaviour is that logger.partitioning is defined before it is called, allowing for the package to be imported. 
Following the traceback shows that logger.partitioning is accessed by way of [line 194 in cf/.__init__.py](https://github.com/NCAS-CMS/cf-python/blob/719e2aa16c39db5e1ac828f5989d67556940be66/cf/__init__.py#L194):
```
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/X/X_env/lib/python3.8/site-packages/cf/__init__.py", line 194, in <module>
    from .mixin import Coordinate
  File "/home/X/X_env/lib/python3.8/site-packages/cf/mixin/__init__.py", line 2, in <module>
    from .propertiesdata import PropertiesData, Subspace
  File "/home/X/X_env/lib/python3.8/site-packages/cf/mixin/propertiesdata.py", line 24, in <module>
    from ..timeduration import TimeDuration
  File "/home/X/X_env/lib/python3.8/site-packages/cf/timeduration.py", line 28, in <module>
    _one_year = Data(1, "calendar_years")
  File "/home/X/X_env/lib/python3.8/site-packages/cf/data/data.py", line 750, in __init__
    self._set_partition_matrix(
  File "/home/X/X_env/lib/python3.8/site-packages/cf/data/data.py", line 832, in _set_partition_matrix
    self.to_disk()
  File "/home/X/X_env/lib/python3.8/site-packages/cf/data/data.py", line 12125, in to_disk
    partition.close()
  File "/home/X/X_env/lib/python3.8/site-packages/cf/data/partition.py", line 788, in close
    logger.partitioning("Partition.close: original = {}".format(original))
AttributeError: 'Logger' object has no attribute 'partitioning'
```
`logger.partitioning` is defined on [line 330 in cf/.__init__.py](https://github.com/NCAS-CMS/cf-python/blob/719e2aa16c39db5e1ac828f5989d67556940be66/cf/__init__.py#L330) and is not created before any submodules are imported. 

A possible solution is to move the logger definitions to before importing the submodules.

**Comment by MirandaLv** [comment]
I had the similar error when I tried to install cf-python on my virtual environment. Here is my steps to install:
1. create a new Conda environment with Conda create -n myenv python=3.8
2. install cf packages following the instructions on https://ncas-cms.github.io/cf-python/installation.html#conda: 
conda install -c ncas -c conda-forge cf-python cf-plot udunits2
conda install -c conda-forge mpich esmpy
3. import cf, received below error message saying AttributeError: 'Logger' object has no attribute 'partitioning'
4. I also tried to install the package from source package, and received the same error.

<img width="717" alt="image" src="https://user-images.githubusercontent.com/3970350/145865370-85b44326-2e9c-459e-85dd-31bfe83e50d4.png">

Any suggestions? Thank you.

**Comment by MirandaLv** [comment]
In case it is useful, below is my Conda list packages:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/3970350/145866421-5df663cc-cab0-4769-aaf9-95eb6faafb9b.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/3970350/145866483-4d40cc08-1c79-4b19-b485-d58cb51744b1.png">

**Comment by MirandaLv** [comment]
@sadielbartholomew I just posted the errors/environments that come with this bug, thank you.

**Comment by sadielbartholomew** [comment]
Hi @MirandaLv, sorry for the delay in replying (we are very busy with urgent pre-Christmas tasks) and thanks for your further report on this, especially for including the necessary detail on your environment and instructions on how to get the right environment.

I will look into this soon, if not later today then early next week. I am still unsure as to how such a critical error is emerging for some and not others, e.g. not showing up on our local and continuous integration testing - if present, I would have thought the error indicated would emerge for everyone, so there is possibly some subtle packaging issue at play here. Regardless of the cause, I will investigate to find out.

Of course, if by following our installation instructions you and @lgouldsbrough and possibly others immediately run into an error, that is a bad bug that needs to be fixed.

When I have more idea what might be going, I will comment here again. Thanks.

**Comment by jocheco** [comment]
Hi @sadielbartholomew, I am really new to the package and also to the whole NetCDF area.

I have just found the same problem using python 3.8 and python 3.9. I managed to get a working version with python 3.7 and cf 3.1. 

Here some information from my side, if it can be of any help. I am working on a Centos8 headless system and the procedure followed in all cases was in the lines of the following listing. Cheers.
  
```
└─ $ > conda create -n rd39 python=3.9
└─ $ > conda activate rd39
└─ $ > conda install -c ncas -c conda-forge cf-python cf-plot udunits2 
└─ $ > python
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/__init__.py", line 207
, in <module>
    from .mixin import Coordinate
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/mixin/__init__.py", li
ne 2, in <module>
    from .propertiesdata import PropertiesData, Subspace
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/mixin/propertiesdata.p
y", line 14, in <module>
    from ..timeduration import TimeDuration
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/timeduration.py", line
 33, in <module>
    _one_year = Data(1, "calendar_years")
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/data/data.py", line 77
2, in __init__
    self._set_partition_matrix(
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/data/data.py", line 85
4, in _set_partition_matrix
    self.to_disk()
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/data/data.py", line 12
148, in to_disk
    partition.close()
  File "/opt/anaconda3/envs/rd39/lib/python3.9/site-packages/cf/data/partition.py", li
ne 792, in close
    logger.partitioning("Partition.close: original = {}".format(original))
AttributeError: 'Logger' object has no attribute 'partitioning'
```
