### ISSUE TITLE
Attempting to install cf-python via pip fails with error

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/cf-python#761]
This is for:
- Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ] on darwin
- (Mac OS 13.6.6 - Ventura - Apple silicon)

It is still the case that conda/mamba installs of cf-python on apple silicon break, but I had expected that pip install would work.
 
But this is what i get:

```
pip install cf
Collecting cf
  Downloading cf-0.41.0.tar.gz (6.5 kB)
  Preparing metadata (setup.py) ... done
Collecting python-cloudfiles (from cf)
  Downloading python-cloudfiles-1.7.11.tar.gz (330 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.7/330.7 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      /private/var/folders/gq/txrkd1kn5zzfjr39ms_lmcxr0000gq/T/pip-install-8jls0zsk/python-cloudfiles_7264b5712cd946ce902916e96efc4660/cloudfiles/__init__.py:1: SyntaxWarning: invalid escape sequence '\ '
        """
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/gq/txrkd1kn5zzfjr39ms_lmcxr0000gq/T/pip-install-8jls0zsk/python-cloudfiles_7264b5712cd946ce902916e96efc4660/setup.py", line 6, in <module>
          from cloudfiles.consts import __version__
        File "/private/var/folders/gq/txrkd1kn5zzfjr39ms_lmcxr0000gq/T/pip-install-8jls0zsk/python-cloudfiles_7264b5712cd946ce902916e96efc4660/cloudfiles/__init__.py", line 82, in <module>
          from cloudfiles.connection     import Connection, ConnectionPool
        File "/private/var/folders/gq/txrkd1kn5zzfjr39ms_lmcxr0000gq/T/pip-install-8jls0zsk/python-cloudfiles_7264b5712cd946ce902916e96efc4660/cloudfiles/connection.py", line 13, in <module>
          from    urllib    import urlencode
      ImportError: cannot import name 'urlencode' from 'urllib' (/Users/bnl28/mambaforge/envs/kermit/lib/python3.12/urllib/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bnlawrence** [comment]
(oooh, hmmm, I think that environment may have had something naughty - for this purpose -  pinned in it, an attempt to install into a pristine python 3.11 works fine. My bad.)
